### PR TITLE
Misc chores

### PR DESCRIPTION
**Pull request by javalsai**
- [x] Add support for more init systems
  - [X] runit
  - [x] openrc
  - [x] s6
- [x] Write man pages
  - [x] Generic man page
  - [x] Talk about config
  - [x] Talk about service files
  - [x] Change AUR pkgbuilds
  - [X] Change flake
- [x] Fix all build warnings. 
  - [x]  `-Wunused-result` missing, can't seem to appear on my system 😔
  - [X] Other warnings
- [x] Add documentation on install methods
  - [x] AUR
  - [x] flake
  - [x] ...
- [x] Work on themes
  - [x] Too many ppl complain abt "swell" and "wuser"... on the default theme
  - [x] Too much "tasteless" and "old blue" themes instead of actual ones that people might want
  - [x] Make new theme screenshots
- [X] Audit config file, currently it's a mess.
  - [X] Audit the rest too (this will be fixed probably with a better config parser, likely toml based)
  - [x] I think all keys have to be specified and keys like `colors.f_other` are unused.
  - [x] There's also inconsistencies as `colors.s_wl` before `colors.s_xorg`, but then having `strings.s_xorg` before `strings.s_wayland` (different name and order)
- [x]  Grammar
  - [x] `codespell` shows a few things...
  - [x] project description is literally "a ✨fully✨ colorful cu~~s~~tomizable TUI"
- [x] CI
  - [x] Simplify build process
  - [x] Consider adding `codespell`
  - [x] Consider adding a C linter/formatter
    - [X] Addded clang-format and [clang-tidy](https://tenor.com/view/byuntear-thousand-yard-stare-cat-soldier-cat-war-scared-gif-12439246475771371280)
    - [x] Put into CI
  - [x] Support more architectures by default
    - [x] aarch64
    - [x] armv7
    - [x] riscv

### CODE REVIEW

**Comment by javalsai** [comment]
I should also make AUR pkgs use `make install DESTDIR="${pkgdir}"` or smth

**Comment by javalsai** [comment]
Finally, done, only gotta test the PKGBUILDS (I need a release for that), but given that only remaining changes are related to AUR pkgs, not anything of code or CI, this can be merged.

I also have to make multiarch pkgs, but that comes after the stuff I mentioned above.

**Comment by javalsai** [comment]
Also, just noticed some markdown indexes

**Comment by javalsai** [comment]
@grialion this done now frfr, approve whenever u want plss

**Review by Pickzelle — APPROVED** [review]
LGTM!

**Pull request merged**
