### PR TITLE
Mostly README changes but other shit too.

### PR DESCRIPTION
**Pull request by DeaDvey**

### CODE REVIEW

**Comment by DeaDvey** [comment]
Wait

**Comment by javalsai** [comment]
Blud wants to get demoted

**Comment by DeaDvey** [comment]
> Blud wants to get demoted

How?

**Comment by DeaDvey** [comment]
Don't pull until morning, I'll look through this more for errors.

**Comment by javalsai** [comment]
Bro's doing my homework 💀

**Comment by DeaDvey** [comment]
> Bro's doing my homework 💀

I'd do anything for you!

**Comment by javalsai** [comment]
Bold of yoh to assume it's LiDM, i don't even know where I got lidm from, so capitalization is technically wrong, or at least not correct. Ur making it up >:(

**Comment by DeaDvey** [comment]
> Bold of yoh to assume it's LiDM, i don't even know where I got lidm from, so capitalization is technically wrong, or at least not correct. Ur making it up >:(

But DM is short for Display Manager so capitalised and L is the first character so capitalised.

**Comment by javalsai** [comment]
> > Bold of yoh to assume it's LiDM, i don't even know where I got lidm from, so capitalization is technically wrong, or at least not correct. Ur making it up >:(
> 
> But DM is short for Display Manager so capitalised and L is the first character so capitalised.

But it's also ckmposed by lid, so it might be LidM, or the `i` might come from simple, so lIdm >:(

**Comment by DeaDvey** [comment]
> > > Bold of yoh to assume it's LiDM, i don't even know where I got lidm from, so capitalization is technically wrong, or at least not correct. Ur making it up >:(
> > 
> > 
> > But DM is short for Display Manager so capitalised and L is the first character so capitalised.
> 
> But it's also ckmposed by lid, so it might be LidM, or the `i` might come from simple, so lIdm >:(

Ok, so you want it ALL lowercase?

**Comment by DeaDvey** [comment]
I uninstall xfce4-session and all the gnome sessions on openSUSE

**Comment by DeaDvey** [comment]
Closed the wrong thing bruh

**Comment by javalsai** [comment]
> > > > Bold of yoh to assume it's LiDM, i don't even know where I got lidm from, so capitalization is technically wrong, or at least not correct. Ur making it up >:(
> > > 
> > > 
> > > But DM is short for Display Manager so capitalised and L is the first character so capitalised.
> > 
> > 
> > But it's also ckmposed by lid, so it might be LidM, or the `i` might come from simple, so lIdm >:(
> 
> Ok, so you want it ALL lowercase?

Idc, if you like LiDM leave it that way

**Comment by javalsai** [comment]
> Closed the wrong thing bruh

yup lol

**Comment by javalsai** [comment]
literally those slips is how ppl commit .env files

**Comment by DeaDvey** [comment]
Can we add lidm to the path like in /usr/bin or smth?

**Comment by DeaDvey** [comment]
During install

**Comment by javalsai** [comment]
> Can we add lidm to the path like in /usr/bin or smth?

make a make script such that `make install` places the binary there, common practice, you could even do a `make install-systemd` too

**Comment by javalsai** [comment]
Just go the makefile and make a `install` rule (clean is another rulenfor example) that copies the file there, I've seen the use of the command `install` for this too, idk how to use it tho. And don't use sudo or anything, it should be run as root by the user.

**Comment by javalsai** [comment]
Same for systemd but with the service file

**Comment by javalsai** [comment]
heheha 😈 I can add commits

**Comment by DeaDvey** [comment]
> heheha 😈 I can add commits

:nerd_face: Yeah duh

**Comment by javalsai** [comment]
Might as well rename the pr to "changes in everything" or smth lol

**Comment by DeaDvey** [comment]
K

**Comment by javalsai** [comment]
I need some of these changes

**Pull request merged**
