### PR TITLE
feat(chvt): use custom implementation instead of system()

### PR DESCRIPTION
**Pull request by grialion**
Calling system() is vulnerable and shouldn't be used.

### CODE REVIEW

**Comment by javalsai** [comment]
LGTM! I'll test it later and merge

**Comment by DeaDvey** [comment]
Imagine contributing code and not just fixing grammar no one cared about :nerd_face:

**Comment by javalsai** [comment]
Naw, why does `(char*)[0]` casted to int work on `ioctl`

**Review by javalsai — APPROVED** [review]
LGTM :+1: 

*look mom, I'm reviewing :)*

**Pull request merged**
