### PR TITLE
fix: misc aur pkg fixes

### PR DESCRIPTION
**Pull request by javalsai**
- lidm package (using release tarball & checksum now)
- config is not executable now

### CODE REVIEW

**Comment by javalsai** [comment]
I was literally braindead when I wrote those PKGBUILDs

**Review by Pickzelle — APPROVED** [review]
LGTM!

**Comment by javalsai** [comment]
I'ma make 0.0.2 with the latest changes too and update the corresponding PKGBUILDS too

**Comment by javalsai** [comment]
ahhhhhh, pkgbuild names x86 as i686, so now the release is invalid cuz I can't do lidm-$pkgver anymore

**Comment by javalsai** [comment]
damn, approvals don't expire on new added commits???

**Pull request merged**
