### PR TITLE
feat: add behavior.{source,user_source} for custom env

### PR DESCRIPTION
**Pull request by javalsai**
I should put this on a release along with the vectors thing which is not in any release so far

Also, aside, I should also clean up readme and docs in general, and threaten people to star the repo at the end of the readme + `https://api.star-history.com/svg?repos=javalsai/lidm&type=Date`. Not sure if in this PR and branch (its not gonna be much) or a new one. If yall think for another PR, pls review this and I'll merge it in a sec.

### CODE REVIEW

**Comment by javalsai** [comment]
And theres also the clang-tidy thing, but I think its too much, it deserves a rewrite tbh.

**Comment by mememan77** [comment]
this cod goo, I aprov :+1:

**Comment by javalsai** [comment]
> this cod goo, I aprov 👍

thats not how reviews works 😭

**Comment by mememan77** [comment]
> > this cod goo, I aprov 👍
> 
> thats not how reviews works 😭

🤓

**Comment by javalsai** [comment]
i shoudl build locally before pushing.....

**Review by Pickzelle — APPROVED** [review]
LGTM!

**Comment by mememan77** [comment]
cod is good :+1:

**Comment by mememan77** [comment]
told u

**Comment by javalsai** [comment]
only thing left is decent readme which ill do separately...

**Review by grialion — COMMENTED** [review]
This is the best commit in this project so far.

**Comment by javalsai** [comment]
> This is the best commit in this project so far.

Which one? Or all the PR?

**Comment by javalsai** [comment]
And false, the best one is https://github.com/javalsai/lidm/commit/255256bb274f4352424c5f82fb2a75c4bc278273

**Comment by grialion** [comment]
4c7d221a176e51aa2529e4e98d536ec2a504e7ae

**Comment by javalsai** [comment]
> [4c7d221](https://github.com/javalsai/lidm/commit/4c7d221a176e51aa2529e4e98d536ec2a504e7ae)

srsly? dam, that was just error commenting on my bad code in vc 😔

**Pull request merged**
